high_intensity_script:
  max_rest: 10
  max_session: 48
  min_rest: 7
  min_session: 42
low_intensity_script:
  max_rest: 10
  max_session: 59
  min_rest: 7
  min_session: 53
port: '56799'
timings:
  break_end: null
  break_start: null
  on_break: false
  script_start: null
dax:
  key: 'sub_1P1ZkFA7n2uRXzFby8B7iQsI'
  secret: '1c8685b2-a4d8-4d04-a72e-467c456dbfbf'