from osrs_utils import general_utils
import numpy as np
import pyscreenshot
import keyboard
import pyautogui


def cooks():
    screen = np.array(pyscreenshot.grab())
    cook = general_utils.find_moving_target(screen, False)
    keyboard.send('space')
    general_utils.random_sleep(0.5, 0.6)
    keyboard.send('1')
    general_utils.random_sleep(0.5, 0.6)
    keyboard.send('space')
    general_utils.random_sleep(0.5, 0.6)
    keyboard.send('space')
    general_utils.random_sleep(0.5, 0.6)
    keyboard.send('space')
    general_utils.random_sleep(0.5, 0.6)
    keyboard.send('1')
    general_utils.random_sleep(0.2, 0.3)
    general_utils.find_moving_target(screen, False)
    general_utils.random_sleep(4.1, 4.5)
    general_utils.random_sleep(0.5, 0.6)
    keyboard.send('space')
    general_utils.random_sleep(1.5, 1.6)
    keyboard.send('space')
    general_utils.random_sleep(1.5, 1.6)
    keyboard.send('space')
    general_utils.random_sleep(1.5, 1.6)
    keyboard.send('space')
    general_utils.random_sleep(1.5, 1.6)
    keyboard.send('space')
    general_utils.random_sleep(1.5, 1.6)
    keyboard.send('space')
    general_utils.random_sleep(1.5, 1.6)
    keyboard.send('space')
    general_utils.random_sleep(1.5, 1.6)
    keyboard.send('space')
    general_utils.random_sleep(1.5, 1.6)
    keyboard.send('esc')


def sheep():
    screen = np.array(pyscreenshot.grab())
    general_utils.find_moving_target(screen, False)
    general_utils.random_sleep(4.1, 4.5)
    keyboard.send('space')
    general_utils.random_sleep(1.5, 1.6)
    keyboard.send('1')
    general_utils.random_sleep(1.5, 1.6)
    keyboard.send('space')
    general_utils.random_sleep(1.5, 1.6)
    keyboard.send('space')
    general_utils.random_sleep(1.5, 1.6)
    keyboard.send('space')
    general_utils.random_sleep(1.5, 1.6)
    keyboard.send('space')
    general_utils.random_sleep(1.5, 1.6)
    keyboard.send('space')
    general_utils.random_sleep(1.5, 1.6)
    keyboard.send('space')
    general_utils.random_sleep(1.5, 1.6)
    keyboard.send('space')
    general_utils.random_sleep(1.5, 1.6)
    keyboard.send('space')
    general_utils.random_sleep(1.5, 1.6)
    keyboard.send('1')
    general_utils.random_sleep(1.5, 1.6)
    keyboard.send('space')
    general_utils.random_sleep(1.5, 1.6)
    keyboard.send('space')
    general_utils.random_sleep(1.5, 1.6)
    keyboard.send('space')
    general_utils.random_sleep(1.5, 1.6)
    keyboard.send('space')
    general_utils.random_sleep(1.5, 1.6)
    keyboard.send('space')
    general_utils.random_sleep(1.5, 1.6)
    keyboard.send('space')
    general_utils.random_sleep(1.5, 1.6)
    keyboard.send('space')
    general_utils.random_sleep(1.5, 1.6)
    keyboard.send('space')
    general_utils.random_sleep(1.5, 1.6)
    keyboard.send('space')
    general_utils.random_sleep(1.5, 1.6)
    keyboard.send('space')